spring:
  application:
    name: credit
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    preferIpAddress: true
    status-page-url-path: /swagger-ui.html
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

